name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: '& "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AX4XfWhdzOxyt2-CNrC-4yO1-TtaIzDNt-qynD4qu_qJ6_uukJvhMQ0-oqupGQOS71qJ2g" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME'
        required: true
      pincode:
        description: '726268'
        required: true
  
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
