name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: chrome remote desktop code
        required: true
      pincode:
        description: password
        required: true
  
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
